'use strict';
const $ = id => document.getElementById(id);
let mondayUsers = [], vrEmployees = [], requestVersion = 0, status = null, querying = false;
const stamp = new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'});
function element(tag,text,className) { const node = document.createElement(tag); if (text != null) node.textContent = text; if(className) node.className=className; return node; }
function dateTime(value) { const d = value ? new Date(value) : null; return d && Number.isFinite(d.getTime()) ? stamp.format(d) : '—'; }
function dateOnly(value) { return /^\d{4}-\d{2}-\d{2}$/.test(String(value)) ? value.split('-').reverse().join('/') : '—'; }
function hours(value,signed=false) { if(value===null || value===undefined || !Number.isFinite(Number(value))) return '—'; const seconds=Number(value), absolute=Math.abs(seconds), minutes=Math.floor(absolute/60), remainder=absolute%60; return `${signed ? seconds < 0 ? '−' : seconds > 0 ? '+' : '' : ''}${Math.floor(minutes/60)}h ${String(minutes%60).padStart(2,'0')}m${remainder ? ` ${String(remainder).padStart(2,'0')}s` : ''}`; }
function normalized(value) { return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toLowerCase(); }
async function api(path,options) { const response=await fetch(path,options); const body=await response.json(); if(!response.ok) throw new Error(body.message||body.error?.message||body.error||'Não foi possível concluir a consulta.'); return body; }
function error(message) { $('page-error').textContent=message; $('page-error').hidden=!message; }
function updateButton() { $('compare-button').disabled=querying || !$('monday-profile').value || !$('vr-profile').value || !$('pair-confirmed').checked || !status?.hasSnapshot; }
function clearResults() { requestVersion++; querying=false; $('comparison-results').hidden=true; $('comparison-body').replaceChildren(); $('empty').hidden=false; $('empty').querySelector('h2').textContent='Uma comparação com a mesma base'; $('empty').querySelector('p').textContent='Confira os perfis e o período, depois clique em Comparar horas.'; error(''); updateButton(); }
function fillSelect(id,people,prompt) { const select=$(id); const empty=element('option',prompt); empty.value=''; const fragment=document.createDocumentFragment(); fragment.append(empty); for(const person of people) { const option=element('option',`${person.name||'Sem nome'}${person.email ? ` · ${person.email}` : ''} · ID ${person.id}`); option.value=String(person.id); fragment.append(option); } select.replaceChildren(fragment); select.disabled=!people.length; }
function suggest() { const user=mondayUsers.find(person=>String(person.id)===$('monday-profile').value); const email=String(user?.email||'').trim().toLowerCase(); const byEmail=email ? vrEmployees.filter(person=>String(person.email||'').trim().toLowerCase()===email) : []; const name=normalized(user?.name); const byName=name ? vrEmployees.filter(person=>normalized(person.name)===name) : []; const candidates=byEmail.length ? byEmail : byName; $('vr-profile').value=''; if(candidates.length===1) { $('vr-profile').value=String(candidates[0].id); $('match-hint').textContent=`Sugestão por ${byEmail.length ? 'e-mail' : 'nome completo'}: ${candidates[0].name}. Confira se é a mesma pessoa e confirme abaixo.`; } else $('match-hint').textContent=candidates.length>1 ? 'Há mais de uma correspondência possível. Escolha o funcionário correto no VR.' : 'Sem correspondência única. Escolha o funcionário no VR e confira os dois perfis.'; }
async function loadPeople() { const results=await Promise.allSettled([api('/api/users'),api('/api/vr/employees')]); if(results[0].status==='fulfilled') { mondayUsers=results[0].value.users||[]; fillSelect('monday-profile',mondayUsers,'Selecione o perfil Monday'); } if(results[1].status==='fulfilled') { vrEmployees=results[1].value.employees||[]; fillSelect('vr-profile',vrEmployees,'Selecione o funcionário VR'); } const failures=results.filter(result=>result.status==='rejected'); if(failures.length) error(failures.map(result=>result.reason.message).join(' · ')); updateButton(); }
function renderStatus(value) { status=value; $('sync-button').disabled=!!value.syncing; $('sync-button').textContent=value.syncing ? 'Sincronizando…' : 'Sincronizar Monday'; $('sync-message').textContent=value.syncing ? `Coleta em andamento · ${value.itemsRead||0} itens lidos` : value.hasSnapshot ? value.complete ? 'Coleta concluída dos itens ativos e subitens deste quadro.' : 'A última tentativa ficou incompleta. Há uma coleta anterior disponível para consulta.' : 'Sincronize o Monday antes de comparar. Ainda não há dados coletados.'; $('sync-details').textContent=`Última coleta concluída: ${dateTime(value.lastSuccessAt)} · ${value.sessionCount||0} sessões. Arquivados e excluídos não entram neste escopo.`; updateButton(); }
async function pollStatus() { try { renderStatus(await api('/api/status')); } catch { $('sync-message').textContent='Não foi possível consultar o estado da coleta Monday.'; } finally { setTimeout(pollStatus,status?.syncing ? 1500 : 8000); } }
const reasonLabels={monday_incomplete:'Coleta Monday incompleta',missing_vr:'Dia não retornado pelo VR',vr_missing:'Dia não retornado pelo VR',vr_unrecognized:'Total VR não reconhecido',open_session:'Relógio em andamento',running_session:'Relógio em andamento',cross_midnight:'Sessão atravessa a meia-noite',overnight_session:'Sessão atravessa a meia-noite',current_day:'Dia em andamento',future_day:'Dia futuro',monday_diagnostics:'Existem ressalvas na qualidade da coleta Monday',no_records:'Sem registros nas duas fontes'};
Object.assign(reasonLabels,{vr_missing_or_unrecognized:'Dia VR ausente ou total não reconhecido',current_or_future_day:'Dia atual ou futuro: fechamento ainda indisponível',cross_midnight_session:'Sessão atravessa a meia-noite: distribuição diária exige revisão',invalid_session_duration:'Sessão com duração inválida',unknown_session_attribution:'Há sessões cuja autoria não pôde ser identificada',no_records_in_both_sources:'Sem registros nas duas fontes: dia excluído do saldo',monday_global_diagnostics:'Qualidade da coleta Monday exige revisão; valores servem apenas como referência'});
function reasonText(code) { return reasonLabels[code] || `Revisão necessária (${String(code).replace(/_/g,' ')})`; }
function safeUrl(value) { try { const url=new URL(value); return url.protocol==='https:' && (url.hostname==='monday.com'||url.hostname.endsWith('.monday.com')) ? url.href : null; } catch { return null; } }
function renderComparison(data) {
  const summary=data.summary||{}, rows=data.rows||[], sources=data.sources||{};
  $('result-person').textContent=mondayUsers.find(person=>String(person.id)===String(data.userId))?.name||'Comparação diária';
  const vrName=vrEmployees.find(person=>String(person.id)===String(data.employeeId))?.name||'Funcionário VR';
  $('result-period').textContent=`${dateOnly(data.from)} a ${dateOnly(data.to)} · VR: ${vrName}`;
  const hasComparable=Number(summary.comparedDays)>0;
  $('total-vr').textContent=hours(hasComparable ? summary.vrSeconds : null); $('total-monday').textContent=hours(hasComparable ? summary.mondaySeconds : null); $('total-difference').textContent=hours(hasComparable ? summary.differenceSeconds : null,true);
  $('total-difference').className=summary.differenceSeconds<0 ? 'difference-negative' : summary.differenceSeconds>0 ? 'difference-positive' : '';
  $('total-coverage').textContent=`${summary.comparedDays||0} / ${rows.length}`; $('coverage-description').textContent=`Dias com cálculo · ${summary.excludedDays||0} excluídos do saldo`;
  $('difference-detail').textContent=hasComparable ? `Na mesma base: ${hours(summary.lessSeconds)} a menos · ${hours(summary.moreSeconds)} a mais · ${hours(summary.absoluteDifferenceSeconds)} de diferenças absolutas. Segundos são exibidos quando presentes, sem tolerância aplicada.` : 'Não há dias com dados suficientes para calcular o saldo.';
  $('warnings').hidden=!data.warnings?.length; $('warnings').replaceChildren(...(data.warnings||[]).map(warning=>element('div',warning.message||reasonText(warning.code))));
  const fragment=document.createDocumentFragment();
  const states={comparable:'A conferir',no_records:'Sem registros',review:'Revisar dados',provisional:'Provisório',missing:'Dados ausentes'};
  for(const [index,day] of rows.entries()) {
    const row=element('tr'), stateCell=element('td'), toggle=element('button','Ver detalhes +','day-toggle'); toggle.type='button'; toggle.setAttribute('aria-expanded','false'); toggle.setAttribute('aria-controls',`day-detail-${index}`);
    stateCell.append(element('span',states[day.state]||'A conferir',`pill ${Object.hasOwn(states,day.state) ? day.state : 'review'}`),toggle);
    row.append(element('td',dateOnly(day.date)),element('td',hours(day.vrSeconds)),element('td',hours(day.mondaySeconds)),element('td',hours(day.differenceSeconds,true)),stateCell);
    const detailRow=element('tr',null,'day-details'); detailRow.id=`day-detail-${index}`; detailRow.hidden=true; const cell=element('td'); cell.colSpan=5;
    if(day.reasons?.length) cell.append(element('p',day.reasons.map(reasonText).join(' · '),'review-reasons'));
    const grid=element('div',null,'detail-grid'), vr=element('div'), monday=element('div'); vr.append(element('h4','Batidas · VR Mais'),element('p',day.timeCards?.length ? day.timeCards.join(' · ') : 'Nenhuma batida retornada.'));
    monday.append(element('h4','Atividades / serviços · Monday')); const list=element('ul'); for(const session of day.sessions||[]) { const li=element('li'), url=safeUrl(session.itemUrl), title=element(url ? 'a' : 'span',session.itemName||`Item ${session.itemId||'—'}`); if(url) { title.href=url; title.target='_blank'; title.rel='noopener noreferrer'; } li.append(title,element('span',` · ${hours(session.durationSeconds)} (total da sessão) · ${dateTime(session.startedAt)} → ${session.running ? 'Em andamento' : dateTime(session.endedAt)}`)); list.append(li); } if(list.childElementCount) monday.append(list); else monday.append(element('p','Nenhuma sessão atribuída a este dia.'));
    grid.append(vr,monday); cell.append(grid); detailRow.append(cell); toggle.addEventListener('click',()=>{ detailRow.hidden=!detailRow.hidden; toggle.setAttribute('aria-expanded',String(!detailRow.hidden)); toggle.textContent=detailRow.hidden ? 'Ver detalhes +' : 'Ocultar detalhes −'; }); fragment.append(row,detailRow);
  }
  $('comparison-body').replaceChildren(fragment); $('sources').textContent=`Monday coletado em ${dateTime(sources.mondaySnapshotAt)} · VR consultado em ${dateTime(sources.vrFetchedAt)}. Os relógios não se atualizam ao vivo nesta tela.`;
  $('empty').hidden=true; $('comparison-results').hidden=false;
}
async function compare(event) { event.preventDefault(); clearResults(); const version=requestVersion; const userId=$('monday-profile').value, employeeId=$('vr-profile').value, from=$('compare-from').value, to=$('compare-to').value; const days=(Date.parse(to)-Date.parse(from))/86400000+1;
  if(!userId||!employeeId||!$('pair-confirmed').checked||!Number.isFinite(days)||days<1||days>31) { error('Confira os dois perfis, confirme a mesma pessoa e escolha um período de até 31 dias.'); return; }
  querying=true; updateButton(); $('empty').querySelector('h2').textContent='Consultando as duas fontes…'; $('empty').querySelector('p').textContent='Buscando os dias no VR e relacionando as sessões Monday do mesmo período.';
  try { const data=await api(`/api/comparison?${new URLSearchParams({userId,employeeId,from,to,confirmed:'true'})}`); if(version!==requestVersion) return; renderComparison(data); }
  catch(failure) { if(version!==requestVersion) return; error(failure.message); $('empty').querySelector('h2').textContent='Não foi possível comparar'; $('empty').querySelector('p').textContent='Confira o aviso acima e tente consultar novamente.'; }
  finally { if(version===requestVersion) { querying=false; updateButton(); } }
}
const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()); const partsMap=Object.fromEntries(parts.map(part=>[part.type,part.value])); const previous=new Date(`${partsMap.year}-${partsMap.month}-${partsMap.day}T12:00:00Z`); previous.setUTCDate(previous.getUTCDate()-1); const end=previous.toISOString().slice(0,10); $('compare-to').value=end; $('compare-from').value=`${end.slice(0,7)}-01`;
$('monday-profile').addEventListener('change',()=>{ $('pair-confirmed').checked=false; suggest(); clearResults(); }); $('vr-profile').addEventListener('change',()=>{ $('pair-confirmed').checked=false; $('match-hint').textContent='Escolha manual. Confirme que os perfis pertencem à mesma pessoa; nenhum vínculo será salvo.'; clearResults(); });
for(const id of ['compare-from','compare-to','pair-confirmed']) $(id).addEventListener('change',clearResults);
$('comparison-form').addEventListener('submit',compare); $('sync-button').addEventListener('click',async()=>{ $('sync-button').disabled=true; clearResults(); try { renderStatus(await api('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})); } catch(failure) { error(failure.message); $('sync-button').disabled=false; } });
loadPeople(); pollStatus();
